---
config:
  look: handDrawn
  theme: neutral
---
flowchart LR
  ME[me, Colab login]
  SEC[Colab secret<br>DHAI_BUCKET]
  REPO[GitHub repo]
  NB[Colab notebook]
  PSA[pipeline-sa]
  TSA["train-sa (M3)"]
  MAIN[(bc-rlhf-reward-2026)]
  HOLD[(holdout bucket)]

  ME --> NB
  SEC --> NB
  REPO --> NB
  NB -.->|same rights as| PSA
  PSA -->|admin| MAIN
  PSA -->|admin| HOLD
  TSA -->|read only| MAIN
  TSA -.-x|no access| HOLD
